### ISSUE TITLE
Error: Could not find

### ISSUE THREAD

**Issue by ntoulasd** [dernasherbrezon/rtlSpectrum#1]
Hi I am trying to run rtlSpectrum and I get

java -jar rtlSpectrum.jar
Error: Could not find or load main class ru.r2cloud.rtlspectrum.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

Also I have
java -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)

**Comment by crlogic** [comment]
Same error received using Buster on a Raspberry Pi

**Comment by dernasherbrezon** [comment]
Fixed in 1.4. Some JDKs 11+ do not have JavaFX.
