### ISSUE TITLE
Error: For input string "-inf"

### ISSUE THREAD

**Issue by zenfish** [dernasherbrezon/rtlSpectrum#2]
My RTL-SDR+rtl_power can return a "-inf" instead of a number (presumably... not much signal there ;)), which results in the subject line as an error at the bottom of the splash screen. This happens . Manually changing the CSV to have something small (e..g. -99 or w/e) makes your program happy again.

Tnx for the nice graphs.

**Comment by dernasherbrezon** [comment]
Fixed in 1.4. I've added gaps in graph instead of -99 values.
