### ISSUE TITLE
Java version pom/README misalignment

### ISSUE THREAD

**Issue by mikeoertli** [dernasherbrezon/rtlSpectrum#3]
Love the project! I noticed that the README says Java 8+, but when I ran with 11 and 13 I get a missing JavaFX dependency at runtime (compile/test is fine). When I downgrade to JDK8, the `maven-compiler-plugin` has issues with the `<release>11</release>` line. Even if you change it to 8, that doesn't work because it seems like the format has to be different (which seems weird to me...). 

I had to use this to run with Java 8:

```
<plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.8.0</version>
    <configuration>
        <source>1.8</source>
        <target>1.8</target>
    </configuration>
</plugin>
```

I'm not sure which java version you want to support or if there's a good way to support both easily, but I'd recommend updating the README to say 11+ and then address the JavaFX runtime dependency (or maybe an issue on my end? I haven't messed with FX much...) Unfortunately I unable to debug and provide more useful feedback at the moment... apologies for not just submitting a PR with a proposed fix.

**Comment by mikeoertli** [comment]
This might be a good option: https://openjfx.io/openjfx-docs/#maven

**Comment by dernasherbrezon** [comment]
Actually it should work with jdk11. Dependency is already there:

```java
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-controls</artifactId>
			<version>11.0.2</version>
		</dependency>
```

Can you try to pull the latest? Another option would be to run pre-compiled .jar from the releases:
https://github.com/dernasherbrezon/rtlSpectrum/releases/download/rtlSpectrum-1.4/rtlSpectrum.jar

**Comment by mikeoertli** [comment]
Thanks for the quick reply and README update. I had the same thought, that's why I was (and remain) confused that it doesn't run for me. 

```
> java -jar target/rtlSpectrum.jar
Error: JavaFX runtime components are missing, and are required to run this application
```

No worries on my end, it's very easy to use Java 8 with FX bundled in the JRE as a "worst case." I still am convinced it's a setup issue on my end, though I did have (and still have) the latest on the `master` branch, using JDK 11.0.6 from adoptopenjdk.net. I haven't tried another OpenJDK yet, but since FX isn't bundled anymore I was assuming that wasn't an issue.

One data point if you're interested... unzipping the jar clearly shows the javafx classes, so they are there (I had confirmed this before posting yesterday too, so nothing new). 

I dug in a bit and found some useful resources, [this one](https://stackoverflow.com/questions/52467561/intellij-cant-recognize-javafx-11-with-openjdk-11/52470141#52470141) was the one that ultimately led to the solution that works for me (it directed me [here](https://github.com/openjfx/samples/blob/master/IDE/IntelliJ/Non-Modular/Maven/hellofx/pom.xml)).

It is interesting to me that the issue isn't consistent. In case it helps... I'm on a Mac and I'm running from CLI (not IntelliJ). 

**Potential Solution**
Adding this plugin to the `pom.xml` and changing my command line did resolve the issue for me. Specifically I run with: `mvn compile javafx:run` rather than `java -jar target/rtlSpectrum.jar`. 

The `pom.xml` addition:
```
<plugin>
	<groupId>org.openjfx</groupId>
	<artifactId>javafx-maven-plugin</artifactId>
	<version>0.0.3</version>
	<configuration>
		<mainClass>ru.r2cloud.rtlspectrum.Main</mainClass>
	</configuration>
</plugin>
```

Anyway, I've taken enough of your time. Thanks for a cool project!

**Comment by dernasherbrezon** [comment]
Ah. Let me try with adoptopenjdk.net. I'm using LibericaJDK and they have javafx bundled.

I prefer to depend only on JDK, rather than JDK + Maven.

**Comment by dernasherbrezon** [comment]
Fixed. Can you try https://github.com/dernasherbrezon/rtlSpectrum/releases/download/rtlSpectrum-1.5/rtlSpectrum.jar ?

java -jar rtlSpectrum.jar

**Comment by mikeoertli** [comment]
Works great! I confirmed with the latest `master` (commit: `04f4e5b3378e68541487ea1744acffb0f75db52b`) and release 1.5.
