### ISSUE TITLE
Raspberry Pi 1

### ISSUE THREAD

**Issue by fruitofgeorge** [dernasherbrezon/rtlSpectrum#5]
I see java 11+ is required but oracle and openjdk don't support v6 architecture of raspberry pi 1. I managed to install the azul zulu 11 jdk but when I try to run rtlSpectrum I still get all kinds of errors, mostly referring to wrong ELF class. Do you know if this should run properly on rPi 1?

**Comment by dernasherbrezon** [comment]
Can you try liberica jdk https://bell-sw.com/pages/downloads/?release=14.0.1+8 ?

**Comment by fruitofgeorge** [comment]
That version immediately crashes with "illegal instruction." Most likely because it is not compatible with ARM v6.

However after many hours of googling, I did manage to get it working. I have no idea how java works but from what I can tell it seems maven was pulling in an incompatible version of openjfx. I had to manually set the java library path to the functioning azul installation so that openjfx could use that library to work.

**Comment by dernasherbrezon** [comment]
Ah makes sense. Thank you for the info!

Currently:
```xml
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-graphics </artifactId>
			<version>${javafx-version}</version>
			<classifier>win</classifier>
		</dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-graphics </artifactId>
			<version>${javafx-version}</version>
			<classifier>linux</classifier>
		</dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-graphics </artifactId>
			<version>${javafx-version}</version>
			<classifier>mac</classifier>
		</dependency>
```

So I guess all native dependencies were built for i386.
